-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Feb 27, 2025 at 06:41 AM
-- Server version: 9.1.0
-- PHP Version: 8.3.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `news`
--

-- --------------------------------------------------------

--
-- Table structure for table `newsarticles`
--

DROP TABLE IF EXISTS `newsarticles`;
CREATE TABLE IF NOT EXISTS `newsarticles` (
  `id` int NOT NULL AUTO_INCREMENT,
  `headline` varchar(500) NOT NULL,
  `link` varchar(1000) NOT NULL,
  `summary` text,
  `source` varchar(255) NOT NULL,
  `scrape_date` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_headline` (`headline`(250)),
  KEY `idx_source` (`source`(250))
) ENGINE=MyISAM AUTO_INCREMENT=102 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `newsarticles`
--

INSERT INTO `newsarticles` (`id`, `headline`, `link`, `summary`, `source`, `scrape_date`) VALUES
(1, 'AI-Powered Social Engineering: Ancillary Tools and Techniques', 'https://thehackernews.com/2025/02/ai-powered-social-engineering-ancillary.html', 'Social engineeringis advancing fast, at the speed of generative AI. This is offering bad actors multiple new tools and techniques for researching, scoping, and exploiting organizations. In a recent communication, the FBI pointed out: \'As technology continues to evolve, so do cybercriminals\' tactics.\'', 'https://thehackernews.com/', '2025-02-15 13:09:32'),
(2, 'Microsoft: Russian-Linked Hackers Using \'Device Code Phishing\' to Hijack Accounts', 'https://thehackernews.com/2025/02/microsoft-russian-linked-hackers-using.html', 'Microsoft is calling attention to an emerging threat cluster it callsStorm-2372that has been attributed to a new set of cyber attacks aimed at a variety of sectors since August 2024.', 'https://thehackernews.com/', '2025-02-15 13:09:33'),
(3, 'Hackers Use CAPTCHA Trick on Webflow CDN PDFs to Bypass Security Scanners', 'https://thehackernews.com/2025/02/hackers-use-captcha-trick-on-webflow.html', 'A widespread phishing campaign has been observed leveraging bogus PDF documents hosted on theWebflowcontent delivery network (CDN) with an aim to steal credit card information and commit financial fraud.', 'https://thehackernews.com/', '2025-02-15 13:09:33'),
(4, 'North Korean APT43 Uses PowerShell and Dropbox in Targeted South Korea Cyberattacks', 'https://thehackernews.com/2025/02/north-korean-apt43-uses-powershell-and.html', 'A nation-state threat actor with ties to North Korea has been linked to an ongoing campaign targeting South Korean business, government, and cryptocurrency sectors.', 'https://thehackernews.com/', '2025-02-15 13:09:34'),
(5, 'Hacking in the name of', 'https://thehackernews.com/expert-insights/2025/02/hacking-in-name-of.html', 'Since Russia\'s latest escalation in 2022 with its invasion of Ukraine, hacktivism has surged, impacting both private and public sectors through DDoS attacks, defacements, and disinformation campaigns. These cyberattacks align with geopolitical events. As 2024 saw over 50 countries holding elections, this creates particularly ripe conditions for influence operations such as misinformation and propaganda campaigns.', 'https://thehackernews.com/', '2025-02-15 13:09:35'),
(6, 'AI-Powered Social Engineering: Ancillary Tools and Techniques', 'https://thehackernews.com/2025/02/ai-powered-social-engineering-ancillary.html', 'Social engineeringis advancing fast, at the speed of generative AI. This is offering bad actors multiple new tools and techniques for researching, scoping, and exploiting organizations. In a recent communication, the FBI pointed out: \'As technology continues to evolve, so do cybercriminals\' tactics.\'', 'https://thehackernews.com/', '2025-02-17 13:14:00'),
(7, 'Microsoft: Russian-Linked Hackers Using \'Device Code Phishing\' to Hijack Accounts', 'https://thehackernews.com/2025/02/microsoft-russian-linked-hackers-using.html', 'Microsoft is calling attention to an emerging threat cluster it callsStorm-2372that has been attributed to a new set of cyber attacks aimed at a variety of sectors since August 2024.', 'https://thehackernews.com/', '2025-02-17 13:14:01'),
(8, 'Hackers Use CAPTCHA Trick on Webflow CDN PDFs to Bypass Security Scanners', 'https://thehackernews.com/2025/02/hackers-use-captcha-trick-on-webflow.html', 'A widespread phishing campaign has been observed leveraging bogus PDF documents hosted on theWebflowcontent delivery network (CDN) with an aim to steal credit card information and commit financial fraud.', 'https://thehackernews.com/', '2025-02-17 13:14:02'),
(9, 'North Korean APT43 Uses PowerShell and Dropbox in Targeted South Korea Cyberattacks', 'https://thehackernews.com/2025/02/north-korean-apt43-uses-powershell-and.html', 'A nation-state threat actor with ties to North Korea has been linked to an ongoing campaign targeting South Korean business, government, and cryptocurrency sectors.', 'https://thehackernews.com/', '2025-02-17 13:14:03'),
(10, 'Hacking in the name of', 'https://thehackernews.com/expert-insights/2025/02/hacking-in-name-of.html', 'Since Russia\'s latest escalation in 2022 with its invasion of Ukraine, hacktivism has surged, impacting both private and public sectors through DDoS attacks, defacements, and disinformation campaigns. These cyberattacks align with geopolitical events. As 2024 saw over 50 countries holding elections, this creates particularly ripe conditions for influence operations such as misinformation and propaganda campaigns.', 'https://thehackernews.com/', '2025-02-17 13:14:04'),
(11, 'New Xerox Printer Flaws Could Let Attackers Capture Windows Active Directory Credentials', 'https://thehackernews.com/2025/02/new-xerox-printer-flaws-could-let.html', 'Security vulnerabilities have been disclosed in Xerox VersaLink C7025 Multifunction printers (MFPs) that could allow attackers to capture authentication credentials via pass-back attacks via Lightweight Directory Access Protocol (LDAP) and SMB/FTP services.', 'https://thehackernews.com/', '2025-02-18 13:07:29'),
(12, 'Cybercriminals Exploit Onerror Event in Image Tags to Deploy Payment Skimmers', 'https://thehackernews.com/2025/02/cybercriminals-exploit-onerror-event-in.html', 'Cybersecurity researchers have flagged a credit card stealing malware campaign that has been observed targeting e-commerce sites running Magento by disguising the malicious content within image tags in HTML code in order to stay under the radar.', 'https://thehackernews.com/', '2025-02-18 13:07:30'),
(13, 'Level Up Your Cyber Skills at SANS 2025', 'https://thehackernews.uk/sans2025-training', 'Free course demos allow you to see course content, watch world-class instructors in action, and evaluate course difficulty.', 'https://thehackernews.com/', '2025-02-18 13:07:34'),
(14, 'South Korea Suspends DeepSeek AI Downloads Over Privacy Violations', 'https://thehackernews.com/2025/02/south-korea-suspends-deepseek-ai.html', 'South Korea has formally suspended new downloads of Chinese artificial intelligence (AI) chatbot DeepSeek in the country until the service makes changes to its mobile apps to comply with data protection regulations.', 'https://thehackernews.com/', '2025-02-18 13:07:34'),
(15, 'AI-Powered Social Engineering: Ancillary Tools and Techniques', 'https://thehackernews.com/2025/02/ai-powered-social-engineering-ancillary.html', 'Social engineeringis advancing fast, at the speed of generative AI. This is offering bad actors multiple new tools and techniques for researching, scoping, and exploiting organizations. In a recent communication, the FBI pointed out: \'As technology continues to evolve, so do cybercriminals\' tactics.\'', 'https://thehackernews.com/', '2025-02-18 13:07:36'),
(16, 'Hacking in the name of', 'https://thehackernews.com/expert-insights/2025/02/hacking-in-name-of.html', 'Since Russia\'s latest escalation in 2022 with its invasion of Ukraine, hacktivism has surged, impacting both private and public sectors through DDoS attacks, defacements, and disinformation campaigns. These cyberattacks align with geopolitical events. As 2024 saw over 50 countries holding elections, this creates particularly ripe conditions for influence operations such as misinformation and propaganda campaigns.', 'https://thehackernews.com/', '2025-02-18 13:07:37'),
(17, 'Level Up Your Cyber Skills at SANS 2025', 'https://thehackernews.uk/sans2025-training', 'Build cyber prowess with training from renowned experts', 'https://thehackernews.com/', '2025-02-19 17:18:19'),
(18, 'Chinese Hackers Exploit MAVInject.exe to Evade Detection in Targeted Cyber Attacks', 'https://thehackernews.com/2025/02/chinese-hackers-exploit-mavinjectexe-to.html', 'The Chinese state-sponsored threat actor known asMustang Pandahas been observed employing a novel technique to evade detection and maintain control over infected systems.', 'https://thehackernews.com/', '2025-02-19 17:18:20'),
(19, 'Winnti APT41 Targets Japanese Firms in RevivalStone Cyber Espionage Campaign', 'https://thehackernews.com/2025/02/winnti-apt41-targets-japanese-firms-in.html', 'The China-linked threat actor known as Winnti has been attributed to a new campaign dubbedRevivalStonethat targeted Japanese companies in the manufacturing, materials, and energy sectors in March 2024.', 'https://thehackernews.com/', '2025-02-19 17:18:21'),
(20, 'New Xerox Printer Flaws Could Let Attackers Capture Windows Active Directory Credentials', 'https://thehackernews.com/2025/02/new-xerox-printer-flaws-could-let.html', 'Security vulnerabilities have been disclosed in Xerox VersaLink C7025 Multifunction printers (MFPs) that could allow attackers to capture authentication credentials via pass-back attacks via Lightweight Directory Access Protocol (LDAP) and SMB/FTP services.', 'https://thehackernews.com/', '2025-02-19 17:18:21'),
(21, 'Cybercriminals Exploit Onerror Event in Image Tags to Deploy Payment Skimmers', 'https://thehackernews.com/2025/02/cybercriminals-exploit-onerror-event-in.html', 'Cybersecurity researchers have flagged a credit card stealing malware campaign that has been observed targeting e-commerce sites running Magento by disguising the malicious content within image tags in HTML code in order to stay under the radar.', 'https://thehackernews.com/', '2025-02-19 17:18:22'),
(22, 'Hacking in the name of', 'https://thehackernews.com/expert-insights/2025/02/hacking-in-name-of.html', 'Since Russia\'s latest escalation in 2022 with its invasion of Ukraine, hacktivism has surged, impacting both private and public sectors through DDoS attacks, defacements, and disinformation campaigns. These cyberattacks align with geopolitical events. As 2024 saw over 50 countries holding elections, this creates particularly ripe conditions for influence operations such as misinformation and propaganda campaigns.', 'https://thehackernews.com/', '2025-02-19 17:18:23'),
(23, 'Level Up Your Cyber Skills at SANS 2025', 'https://thehackernews.uk/sans2025-training', 'Build cyber prowess with training from renowned experts', 'https://thehackernews.com/', '2025-02-20 13:19:12'),
(24, 'Chinese Hackers Exploit MAVInject.exe to Evade Detection in Targeted Cyber Attacks', 'https://thehackernews.com/2025/02/chinese-hackers-exploit-mavinjectexe-to.html', 'The Chinese state-sponsored threat actor known asMustang Pandahas been observed employing a novel technique to evade detection and maintain control over infected systems.', 'https://thehackernews.com/', '2025-02-20 13:19:13'),
(25, 'Hacking in the name of', 'https://thehackernews.com/expert-insights/2025/02/hacking-in-name-of.html', 'Since Russia\'s latest escalation in 2022 with its invasion of Ukraine, hacktivism has surged, impacting both private and public sectors through DDoS attacks, defacements, and disinformation campaigns. These cyberattacks align with geopolitical events. As 2024 saw over 50 countries holding elections, this creates particularly ripe conditions for influence operations such as misinformation and propaganda campaigns.', 'https://thehackernews.com/', '2025-02-20 13:19:14'),
(26, '5 Active Malware Campaigns in Q1 2025', 'https://thehackernews.com/2025/02/5-active-malware-campaigns-in-q1-2025.html', 'The first quarter of 2025 has been a battlefield in the world of cybersecurity. Cybercriminals continued launching aggressive new campaigns and refining their attack methods.', 'https://thehackernews.com/', '2025-02-25 19:13:46'),
(27, 'GitVenom Malware Steals $456K in Bitcoin Using Fake GitHub Projects to Hijack Wallets', 'https://thehackernews.com/2025/02/gitvenom-malware-steals-456k-in-bitcoin.html', 'Cybersecurity researchers are calling attention to an ongoing campaign that\'s targeting gamers and cryptocurrency investors under the guise of open-source projectshosted on GitHub.', 'https://thehackernews.com/', '2025-02-25 19:13:46'),
(28, 'New Malware Campaign Uses Cracked Software to Spread Lumma and ACR Stealer', 'https://thehackernews.com/2025/02/new-malware-campaign-uses-cracked.html', 'Cybersecurity researchers are warning of a new campaign that leverages cracked versions of software as a lure to distribute information stealers like Lumma and ACR Stealer.', 'https://thehackernews.com/', '2025-02-25 19:13:47'),
(29, 'Becoming Ransomware Ready: Why Continuous Validation Is Your Best Defense', 'https://thehackernews.com/2025/02/becoming-ransomware-ready-why.html', 'Ransomware doesn\'t hit all at once—it slowly floods your defenses in stages. Like a ship subsumed with water, the attack starts quietly, below the surface, with subtle warning signs that are easy to miss. By the time encryption starts, it\'s too late to stop the flood.', 'https://thehackernews.com/', '2025-02-25 19:13:47'),
(30, 'Hacking in the name of', 'https://thehackernews.com/expert-insights/2025/02/hacking-in-name-of.html', 'Since Russia\'s latest escalation in 2022 with its invasion of Ukraine, hacktivism has surged, impacting both private and public sectors through DDoS attacks, defacements, and disinformation campaigns. These cyberattacks align with geopolitical events. As 2024 saw over 50 countries holding elections, this creates particularly ripe conditions for influence operations such as misinformation and propaganda campaigns.', 'https://thehackernews.com/', '2025-02-25 19:13:48'),
(31, 'DeepSeek rushes to launch new AI model as China goes all in', 'https://www.reuters.com/technology/', 'Could not fetch article content', 'https://www.reuters.com/technology/', '2025-02-25 19:13:55'),
(32, 'CISA Adds Microsoft and Zimbra Flaws to KEV Catalog Amid Active Exploitation', 'https://thehackernews.com/2025/02/cisa-adds-microsoft-and-zimbra-flaws-to.html', 'The U.S. Cybersecurity and Infrastructure Security Agency (CISA) on Tuesdayplacedtwo security flaws impacting Microsoft Partner Center and Synacor Zimbra Collaboration Suite (ZCS) to its Known Exploited Vulnerabilities (KEV) catalog, based on evidence of active exploitation.', 'https://thehackernews.com/', '2025-02-26 10:07:51'),
(33, 'LightSpy Expands to 100+ Commands, Increasing Control Over Windows, macOS, Linux, and Mobile', 'https://thehackernews.com/2025/02/lightspy-expands-to-100-commands.html', 'Cybersecurity researchers have flagged an updated version of the LightSpy implant that comes equipped with an expanded set of data collection features to extract information from social media platforms like Facebook and Instagram.', 'https://thehackernews.com/', '2025-02-26 10:07:51'),
(34, 'Belarus-Linked Ghostwriter Uses Macropack-Obfuscated Excel Macros to Deploy Malware', 'https://thehackernews.com/2025/02/belarus-linked-ghostwriter-uses.html', 'Opposition activists in Belarus as well as Ukrainian military and government organizations are the target of a new campaign that employs malware-laced Microsoft Excel documents as lures to deliver a new variant ofPicassoLoader.', 'https://thehackernews.com/', '2025-02-26 10:07:52'),
(35, 'State of Code Security in 2025: Key Trends and Threats', 'https://thehackernews.uk/code-security-2025', 'From exposed secrets and public repositories to risky CI/CD practices, our research reveals that the convenience of modern development often makes security more challenging. With the right approach, the two can coexist.', 'https://thehackernews.com/', '2025-02-26 10:07:54'),
(36, '5 Active Malware Campaigns in Q1 2025', 'https://thehackernews.com/2025/02/5-active-malware-campaigns-in-q1-2025.html', 'The first quarter of 2025 has been a battlefield in the world of cybersecurity. Cybercriminals continued launching aggressive new campaigns and refining their attack methods.', 'https://thehackernews.com/', '2025-02-26 10:07:54'),
(37, '2,500+ Truesight.sys Driver Variants Exploited to Bypass EDR and Deploy HiddenGh0st RAT', 'https://thehackernews.com/2025/02/2500-truesightsys-driver-variants.html', 'A large-scale malware campaign has been found leveraging a vulnerable Windows driver associated with Adlice\'s product suite to sidestep detection efforts and deliver theGh0st RAT malware.', 'https://thehackernews.com/', '2025-02-26 10:07:55'),
(38, 'GitVenom Malware Steals $456K in Bitcoin Using Fake GitHub Projects to Hijack Wallets', 'https://thehackernews.com/2025/02/gitvenom-malware-steals-456k-in-bitcoin.html', 'Cybersecurity researchers are calling attention to an ongoing campaign that\'s targeting gamers and cryptocurrency investors under the guise of open-source projectshosted on GitHub.', 'https://thehackernews.com/', '2025-02-26 10:07:55'),
(39, 'Two Actively Exploited Security Flaws in Adobe and Oracle Products Flagged by CISA', 'https://thehackernews.com/2025/02/two-actively-exploited-security-flaws.html', 'The U.S. Cybersecurity and Infrastructure Security Agency (CISA) hasaddedtwo security flaws impacting Adobe ColdFusion and Oracle Agile Product Lifecycle Management (PLM) to its Known Exploited Vulnerabilities (KEV) catalog, based on evidence of active exploitation.', 'https://thehackernews.com/', '2025-02-26 10:07:56'),
(40, 'New Malware Campaign Uses Cracked Software to Spread Lumma and ACR Stealer', 'https://thehackernews.com/2025/02/new-malware-campaign-uses-cracked.html', 'Cybersecurity researchers are warning of a new campaign that leverages cracked versions of software as a lure to distribute information stealers like Lumma and ACR Stealer.', 'https://thehackernews.com/', '2025-02-26 10:07:56'),
(41, 'How Hackers Exploit Your Attack Surface (And How to Protect Yourself)', 'https://thehackernews.com/expert-insights/2025/02/how-hackers-exploit-your-attack-surface.html', 'Hackers are constantly scanning your network, often spotting vulnerabilities before you do. They\'re looking for misconfigurations, exposed assets, and weak points that could lead to a breach—are you seeing what they see? Every activity or interaction that your organization does online – website, social media accounts, cloud services, third-party integrations, and more – contributes to its digital footprint. This digital footprint is information attackers use to find your weaknesses and attempt to exploit them.', 'https://thehackernews.com/', '2025-02-26 10:07:57'),
(42, 'Hacking in the name of', 'https://thehackernews.com/expert-insights/2025/02/hacking-in-name-of.html', 'Since Russia\'s latest escalation in 2022 with its invasion of Ukraine, hacktivism has surged, impacting both private and public sectors through DDoS attacks, defacements, and disinformation campaigns. These cyberattacks align with geopolitical events. As 2024 saw over 50 countries holding elections, this creates particularly ripe conditions for influence operations such as misinformation and propaganda campaigns.', 'https://thehackernews.com/', '2025-02-26 10:07:57'),
(43, '7 Best Web Hosting Services 2025: Features, Price & More', 'https://www.techrepublic.com/', 'The best web hosting services of 2025 offer fast speeds, strong security, and reliable uptime. Explore top-rated providers to find the perfect fit for your website.', 'https://www.techrepublic.com/', '2025-02-26 10:08:00'),
(44, '6 Best Recurring Billing Software in 2025', 'https://www.techrepublic.com/', 'The best web hosting services of 2025 offer fast speeds, strong security, and reliable uptime. Explore top-rated providers to find the perfect fit for your website.', 'https://www.techrepublic.com/', '2025-02-26 10:08:01'),
(45, 'NordPass vs LastPass: Compare Features, Security, and Pricing for 2025', 'https://www.techrepublic.com/', 'The best web hosting services of 2025 offer fast speeds, strong security, and reliable uptime. Explore top-rated providers to find the perfect fit for your website.', 'https://www.techrepublic.com/', '2025-02-26 10:08:01'),
(46, 'The 7 Best Money Saving Apps Reviewed for 2025', 'https://www.techrepublic.com/', 'The best web hosting services of 2025 offer fast speeds, strong security, and reliable uptime. Explore top-rated providers to find the perfect fit for your website.', 'https://www.techrepublic.com/', '2025-02-26 10:08:02'),
(47, 'LogRhythm vs Splunk (2025): SIEM Tool Comparison', 'https://www.techrepublic.com/', 'The best web hosting services of 2025 offer fast speeds, strong security, and reliable uptime. Explore top-rated providers to find the perfect fit for your website.', 'https://www.techrepublic.com/', '2025-02-26 10:08:02'),
(48, '7 Best Web Hosting Services 2025: Features, Price & More', 'https://www.techrepublic.com/', 'The best web hosting services of 2025 offer fast speeds, strong security, and reliable uptime. Explore top-rated providers to find the perfect fit for your website.', 'https://www.techrepublic.com/', '2025-02-26 10:08:02'),
(49, '6 Best Recurring Billing Software in 2025', 'https://www.techrepublic.com/', 'The best web hosting services of 2025 offer fast speeds, strong security, and reliable uptime. Explore top-rated providers to find the perfect fit for your website.', 'https://www.techrepublic.com/', '2025-02-26 10:08:03'),
(50, 'NordPass vs LastPass: Compare Features, Security, and Pricing for 2025', 'https://www.techrepublic.com/', 'The best web hosting services of 2025 offer fast speeds, strong security, and reliable uptime. Explore top-rated providers to find the perfect fit for your website.', 'https://www.techrepublic.com/', '2025-02-26 10:08:03'),
(51, '7 Best Payroll Software for UK Businesses in 2025', 'https://www.techrepublic.com/', 'The best web hosting services of 2025 offer fast speeds, strong security, and reliable uptime. Explore top-rated providers to find the perfect fit for your website.', 'https://www.techrepublic.com/', '2025-02-26 10:08:04'),
(52, 'Westlaw, opens new tabBuild the strongest argument relying on authoritative content, attorney-editor expertise, and industry defining technology.', 'https://www.reuters.com/technology/', 'Could not fetch article content', 'https://www.reuters.com/technology/', '2025-02-26 10:08:08'),
(53, 'ONESOURCE, opens new tabThe most comprehensive solution to manage all your complex and ever-expanding tax and compliance needs.', 'https://www.reuters.com/technology/', 'Could not fetch article content', 'https://www.reuters.com/technology/', '2025-02-26 10:08:08'),
(54, 'Checkpoint, opens new tabThe industry leader for online information for tax, accounting and finance professionals.', 'https://www.reuters.com/technology/', 'Could not fetch article content', 'https://www.reuters.com/technology/', '2025-02-26 10:08:08'),
(55, 'Workspace, opens new tabAccess unmatched financial data, news and content in a highly-customised workflow experience on desktop, web and mobile.', 'https://www.reuters.com/technology/', 'Could not fetch article content', 'https://www.reuters.com/technology/', '2025-02-26 10:08:08'),
(56, 'DataCatalogue, opens new tabBrowse an unrivalled portfolio of real-time and historical market data and insights from worldwide sources and experts.', 'https://www.reuters.com/technology/', 'Could not fetch article content', 'https://www.reuters.com/technology/', '2025-02-26 10:08:09'),
(57, 'World-Check, opens new tabScreen for heightened risk individual and entities globally to help uncover hidden risks in business relationships and human networks.', 'https://www.reuters.com/technology/', 'Could not fetch article content', 'https://www.reuters.com/technology/', '2025-02-26 10:08:09'),
(58, 'Belarus-Linked Ghostwriter Uses Macropack-Obfuscated Excel Macros to Deploy Malware', 'https://thehackernews.com/2025/02/belarus-linked-ghostwriter-uses.html', 'Opposition activists in Belarus as well as Ukrainian military and government organizations are the target of a new campaign that employs malware-laced Microsoft Excel documents as lures to deliver a new variant ofPicassoLoader.', 'https://thehackernews.com/', '2025-02-26 10:12:32'),
(59, 'State of Code Security in 2025: Key Trends and Threats', 'https://thehackernews.uk/code-security-2025', 'From exposed secrets and public repositories to risky CI/CD practices, our research reveals that the convenience of modern development often makes security more challenging. With the right approach, the two can coexist.', 'https://thehackernews.com/', '2025-02-26 10:12:33'),
(60, '5 Active Malware Campaigns in Q1 2025', 'https://thehackernews.com/2025/02/5-active-malware-campaigns-in-q1-2025.html', 'The first quarter of 2025 has been a battlefield in the world of cybersecurity. Cybercriminals continued launching aggressive new campaigns and refining their attack methods.', 'https://thehackernews.com/', '2025-02-26 10:12:34'),
(61, 'GitVenom Malware Steals $456K in Bitcoin Using Fake GitHub Projects to Hijack Wallets', 'https://thehackernews.com/2025/02/gitvenom-malware-steals-456k-in-bitcoin.html', 'Cybersecurity researchers are calling attention to an ongoing campaign that\'s targeting gamers and cryptocurrency investors under the guise of open-source projectshosted on GitHub.', 'https://thehackernews.com/', '2025-02-26 10:12:34'),
(62, 'New Malware Campaign Uses Cracked Software to Spread Lumma and ACR Stealer', 'https://thehackernews.com/2025/02/new-malware-campaign-uses-cracked.html', 'Cybersecurity researchers are warning of a new campaign that leverages cracked versions of software as a lure to distribute information stealers like Lumma and ACR Stealer.', 'https://thehackernews.com/', '2025-02-26 10:12:35'),
(63, 'Hacking in the name of', 'https://thehackernews.com/expert-insights/2025/02/hacking-in-name-of.html', 'Since Russia\'s latest escalation in 2022 with its invasion of Ukraine, hacktivism has surged, impacting both private and public sectors through DDoS attacks, defacements, and disinformation campaigns. These cyberattacks align with geopolitical events. As 2024 saw over 50 countries holding elections, this creates particularly ripe conditions for influence operations such as misinformation and propaganda campaigns.', 'https://thehackernews.com/', '2025-02-26 10:12:35'),
(64, '7 Best Web Hosting Services 2025: Features, Price & More', 'https://www.techrepublic.com/', 'The best web hosting services of 2025 offer fast speeds, strong security, and reliable uptime. Explore top-rated providers to find the perfect fit for your website.', 'https://www.techrepublic.com/', '2025-02-26 10:12:39'),
(65, '6 Best Recurring Billing Software in 2025', 'https://www.techrepublic.com/', 'The best web hosting services of 2025 offer fast speeds, strong security, and reliable uptime. Explore top-rated providers to find the perfect fit for your website.', 'https://www.techrepublic.com/', '2025-02-26 10:12:40'),
(66, 'NordPass vs LastPass: Compare Features, Security, and Pricing for 2025', 'https://www.techrepublic.com/', 'The best web hosting services of 2025 offer fast speeds, strong security, and reliable uptime. Explore top-rated providers to find the perfect fit for your website.', 'https://www.techrepublic.com/', '2025-02-26 10:12:40'),
(67, 'The 7 Best Money Saving Apps Reviewed for 2025', 'https://www.techrepublic.com/', 'The best web hosting services of 2025 offer fast speeds, strong security, and reliable uptime. Explore top-rated providers to find the perfect fit for your website.', 'https://www.techrepublic.com/', '2025-02-26 10:12:40'),
(68, 'LogRhythm vs Splunk (2025): SIEM Tool Comparison', 'https://www.techrepublic.com/', 'The best web hosting services of 2025 offer fast speeds, strong security, and reliable uptime. Explore top-rated providers to find the perfect fit for your website.', 'https://www.techrepublic.com/', '2025-02-26 10:12:41'),
(69, '7 Best Web Hosting Services 2025: Features, Price & More', 'https://www.techrepublic.com/', 'The best web hosting services of 2025 offer fast speeds, strong security, and reliable uptime. Explore top-rated providers to find the perfect fit for your website.', 'https://www.techrepublic.com/', '2025-02-26 10:12:41'),
(70, '6 Best Recurring Billing Software in 2025', 'https://www.techrepublic.com/', 'The best web hosting services of 2025 offer fast speeds, strong security, and reliable uptime. Explore top-rated providers to find the perfect fit for your website.', 'https://www.techrepublic.com/', '2025-02-26 10:12:41'),
(71, 'NordPass vs LastPass: Compare Features, Security, and Pricing for 2025', 'https://www.techrepublic.com/', 'The best web hosting services of 2025 offer fast speeds, strong security, and reliable uptime. Explore top-rated providers to find the perfect fit for your website.', 'https://www.techrepublic.com/', '2025-02-26 10:12:42'),
(72, '7 Best Payroll Software for UK Businesses in 2025', 'https://www.techrepublic.com/', 'The best web hosting services of 2025 offer fast speeds, strong security, and reliable uptime. Explore top-rated providers to find the perfect fit for your website.', 'https://www.techrepublic.com/', '2025-02-26 10:12:42'),
(73, 'Leaked Black Basta Ransomware Chat Logs Reveal Inner Workings and Internal Conflicts', 'https://thehackernews.com/2025/02/leaked-black-basta-chat-logs-reveal.html', 'More than a year\'s worth of internal chat logs from a ransomware gang known as Black Basta have beenpublished onlinein a leak that provides unprecedented visibility into their tactics and internal conflicts among its members.', 'https://thehackernews.com/', '2025-02-27 12:03:55'),
(74, 'New Linux Malware \'Auto-Color\' Grants Hackers Full Remote Access to Compromised Systems', 'https://thehackernews.com/2025/02/new-linux-malware-auto-color-grants.html', 'Universities and government organizations in North America and Asia have been targeted by a previously undocumented Linux malware called Auto-Color between November and December 2024, according to new findings from Palo Alto Networks Unit 42.', 'https://thehackernews.com/', '2025-02-27 12:03:55'),
(75, 'CERT-UA Warns of UAC-0173 Attacks Deploying DCRat to Compromise Ukrainian Notaries', 'https://thehackernews.com/2025/02/cert-ua-warns-of-uac-0173-attacks.html', 'The Computer Emergency Response Team of Ukraine (CERT-UA) on Tuesday warned of renewed activity from an organized criminal group it tracks as UAC-0173 that involves infecting computers with a remote access trojan namedDCRat(aka DarkCrystal RAT).', 'https://thehackernews.com/', '2025-02-27 12:03:56'),
(76, 'Belarus-Linked Ghostwriter Uses Macropack-Obfuscated Excel Macros to Deploy Malware', 'https://thehackernews.com/2025/02/belarus-linked-ghostwriter-uses.html', 'Opposition activists in Belarus as well as Ukrainian military and government organizations are the target of a new campaign that employs malware-laced Microsoft Excel documents as lures to deliver a new variant ofPicassoLoader.', 'https://thehackernews.com/', '2025-02-27 12:03:56'),
(77, '5 Active Malware Campaigns in Q1 2025', 'https://thehackernews.com/2025/02/5-active-malware-campaigns-in-q1-2025.html', 'The first quarter of 2025 has been a battlefield in the world of cybersecurity. Cybercriminals continued launching aggressive new campaigns and refining their attack methods.', 'https://thehackernews.com/', '2025-02-27 12:03:57'),
(78, 'Hacking in the name of', 'https://thehackernews.com/expert-insights/2025/02/hacking-in-name-of.html', 'Since Russia\'s latest escalation in 2022 with its invasion of Ukraine, hacktivism has surged, impacting both private and public sectors through DDoS attacks, defacements, and disinformation campaigns. These cyberattacks align with geopolitical events. As 2024 saw over 50 countries holding elections, this creates particularly ripe conditions for influence operations such as misinformation and propaganda campaigns.', 'https://thehackernews.com/', '2025-02-27 12:03:58'),
(79, 'Ransomware Attacks are on the Rise', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:07'),
(80, 'Cloud Security: The Forecast for 2022', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:08'),
(81, '2021: The Evolution of Ransomware', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:09'),
(82, 'Cybercriminals Are Selling Access to Chinese Surveillance Cameras', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:11'),
(83, 'Firewall Bug Under Active Attack Triggers CISA Warning', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:12'),
(84, 'Top 5 Tips to Avoid Viruses and Spyware', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:15'),
(85, 'U.S. needs to investigate cyberweapons', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:16'),
(86, 'Protecting Phones From Pegasus-Like Spyware Attacks', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:18'),
(87, 'Spotlight on Cybercriminal Supply Chains', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:19'),
(88, 'Breaking Down Joe Biden’s $10B Cybersecurity ‘Down Payment’', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:24'),
(89, 'Cyber-Spike: Orgs Suffer 925 Attacks per Week, an All-Time High', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:25'),
(90, 'PYSA Emerges as Top Ransomware Actor in November', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:29'),
(91, 'Encrypted & Fileless Malware Sees Big Growth', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:31'),
(92, 'Cyberattackers Put the Pedal to the Medal: Podcast', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:34'),
(93, 'MacOS Malware: Myth vs. Truth – Podcast', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:35'),
(94, 'Lyceum APT Returns, This Time Targeting Tunisian Firms', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:36'),
(95, 'Malware Gangs Partner Up in Double-Punch Security Threat', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:38'),
(96, 'Ransomware and IP Theft: Top COVID-19 Healthcare Security Scares', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:39'),
(97, 'Cybercriminals Step Up Their Game Ahead of U.S. Elections', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:40'),
(98, '2020 Cybersecurity Trends to Watch', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:42'),
(99, 'Biggest Malware Threats of 2019', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:43'),
(100, '2019 Malware Trends to Watch', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:46'),
(101, '2019: The Year Ahead in Cybersecurity', 'https://threatpost.com/', '2.5 million people were affected, in a breach that could spell more trouble down the line.', 'https://threatpost.com/', '2025-02-27 12:04:51');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
